[project]
name = "orchestration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "clickhouse-connect>=0.8.18",
    "prefect>=3.4.6",
    "prefect-aws>=0.5.10",
    "python-dotenv>=1.1.0",
]
