[project]
name = "ai-image-detection"
version = "0.1.0"
description = "Code related to AI image detection"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gputil>=1.4.0",
    "imagehash>=4.3.2",
    "pillow>=11.3.0",
    "transformers[torch]>=4.56.2",
]
